name: mivent
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  boxy: ^2.0.5+1 #
  encrypt: ^5.0.1
  dartz: ^0.10.1
  http: #
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  fluttertoast: ^8.0.9
  google_maps_flutter: ^2.0.6
  google_sign_in: ^5.3.0
  hive_flutter: ^1.1.0
  image_picker: ^0.8.4+2
  map_launcher: ^2.2.1+2
  nanoid: ^1.0.0
  photo_view: ^0.13.0 #
  mobile_scanner: ^1.0.0
  #qr_code_scanner: ^0.7.0
  qr_flutter: ^4.0.0
  share_plus: ^4.0.4
  upgrader: ^3.15.0
  url_launcher:

  flutterwave_standard:
    path: ../_packages/flutterwave_standard-1.0.3/

  fancy_bottom_navigation: #
    path: ../_packages/fancy_bottom_navigation-0.3.3/

  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_dynamic_links: ^4.2.2
  firebase_storage: ^10.2.12
  cloud_firestore: ^3.1.12

  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter


dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.2

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Lucette
      fonts:
        - asset: assets/fonts/lucette_regular.ttf
    - family: Mivent
      fonts:
        - asset: assets/fonts/Mivent.ttf