// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIPhB9yKgeftokZrCIF4jfVvfZ4VLdq3w',
    appId: '1:1082982386784:android:6916bc24db16c9cd088705',
    messagingSenderId: '1082982386784',
    projectId: 'mivent-app',
    storageBucket: 'mivent-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxpdDOpUke2260lFssk8DRdT-vt_aMlnk',
    appId: '1:1082982386784:ios:a7f01a1c8b852d01088705',
    messagingSenderId: '1082982386784',
    projectId: 'mivent-app',
    storageBucket: 'mivent-app.appspot.com',
    androidClientId: '1082982386784-saj42uaad9gkt2tbkb3stbdol4frkrhm.apps.googleusercontent.com',
    iosClientId: '1082982386784-ica9m9qf2l9t7lejck52esqqnatl7t1l.apps.googleusercontent.com',
    iosBundleId: 'co',
  );
}
