// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJu78hvsDx2I8O00LrfwwjRtItqy9WuX8',
    appId: '1:1082982386784:web:1ff2c7782d729a7b088705',
    messagingSenderId: '1082982386784',
    projectId: 'mivent-app',
    authDomain: 'mivent-app.firebaseapp.com',
    storageBucket: 'mivent-app.appspot.com',
    measurementId: 'G-S0ZVLHD8G6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0aHwUlKnmhxS-waAfFp9iZ6CvS80Hb8o',
    appId: '1:1082982386784:android:2501389e3219e16d088705',
    messagingSenderId: '1082982386784',
    projectId: 'mivent-app',
    storageBucket: 'mivent-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxpdDOpUke2260lFssk8DRdT-vt_aMlnk',
    appId: '1:1082982386784:ios:70befad77a80128c088705',
    messagingSenderId: '1082982386784',
    projectId: 'mivent-app',
    storageBucket: 'mivent-app.appspot.com',
    androidClientId: '1082982386784-i8rilcihjs15volgvq5eaqeq9rbdi5vt.apps.googleusercontent.com',
    iosClientId: '1082982386784-t2e30qpg8hickppsrkrh9ajqpgc33er0.apps.googleusercontent.com',
    iosBundleId: 'com.example.mivent',
  );
}
